### ISSUE TITLE
changeSetting 类型问题

### ISSUE THREAD

**Issue by GGGLHHH** [WalkAlone0325/tsx-naive-admin#3]
import type { SettingConfig } from '@/settings'
import settings from '@/settings'
import type { TriggerStyle } from '@/settings'

export const useSettingStore = defineStore('setting', () => {
  const setting = reactive(settings)

  const changeSetting = <T extends keyof SettingConfig>(
    key: T,
    value: SettingConfig[T]
  ) => {
    setting[key] = value
  }

  return {
    ...toRefs(setting),
    changeSetting
  }
})

**Comment by WalkAlone0325** [comment]
试了下也不行啊，这里试过很多方法，不知道怎么写。或者可以直接加 ts 注释先跳过检查

**Comment by GGGLHHH** [comment]
![image](https://user-images.githubusercontent.com/58617090/197095666-6c50bda3-5b20-48d5-8954-6a620e0677ac.png)
代码没贴全，应该是可以的。
