### ISSUE TITLE
KeepAlive问题

### ISSUE THREAD

**Issue by GGGLHHH** [WalkAlone0325/tsx-naive-admin#4]
![image](https://user-images.githubusercontent.com/58617090/197152463-218610ca-c866-4bd4-9fd2-44bf0e434fa3.png)
你的KeepAlive缓存是无作用的。这种写法有效。
但是我不清楚Component的类型先写个any，如果你知道的话麻烦告诉我一下
还有一个问题就是我还没有实现Transition和KeepAlive共同使用时的切换效果，希望你能一起看看

**Comment by GGGLHHH** [comment]
我找到了同时使用的写法
![image](https://user-images.githubusercontent.com/58617090/197157329-47af9f60-dc75-4e31-b98c-a6e226c1a9e0.png)
他在组件使用空标签<></>包裹根views组件时会报错，不清楚原因

**Comment by WalkAlone0325** [comment]
`Component` 的类型是 `VNode`，文档有写。整体的参考
```tsx
<RouterView>
        {{
          default: ({ Component }: { Component: VNode }) => (
            <Transition
              mode="out-in"
              name="fade"
            >
              <KeepAlive>
                <Suspense>
                  {{
                    default: () => h(Component),
                    fallback: () => '正在加载。。。'
                  }}
                </Suspense>
              </KeepAlive>
            </Transition>
          )
        }}
      </RouterView>
```

他在组件使用空标签<></>包裹根views组件时会报错  没看懂。
最近抽时间在重写（但也是比较忙，有点慢），`KeepAlive` 缓存那块需要组件 `name`， 我还没有完善

**Comment by GGGLHHH** [comment]
Suspense好像又有新的问题，快速切换路由时会报错。。
